---
title: "Syllabus for MEDB5507, Introduction to SAS"
author: "Steve Simon"
date: "July 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
# I will not use too much R in a class called "Introduction to SAS,"
# but am including this chunk just in case I need something from R.
knitr::opts_chunk$set(echo = FALSE)
```

# MEDB 5507, Introduction to SAS 

## Fall 2018, Online, Asynchronous Canvas Course Site

## INTRODUCTION

A working knowledge of statistical software is a vital skill for anyone involved in quantitative research. This course will introduce data management, simple descriptive statistics, and basic graphical display using the SAS software package. Students will develop the fundamental skills needed to prepare datasets for analysis, and to conduct simple descriptive and graphic analyses and report those analyses. 

### Course Description

This course will to provide a working familiarity with SAS. Students are not expected to have advanced programming or statistical analysis skills other than the ability to create and modify text files. A basic understanding of statistical terminology and a working familiarity with computer-based data files (e.g., Excel) is necessary. The class will introduce basic methods for data import, data management, simple graphics, and basic statistical analysis. This class will not cover advanced statistical methods, but will provide you with a firm foundation to address these areas in your advanced statistics classes or in your research efforts, including thesis/dissertation research. 

### Student Learning Objectives

At the completion of this course, students will be able to:

*	Prepare and manipulate datasets for analysis in SAS.
*	Conduct simple descriptive and graphic analyses of data in SAS.
*	Prepare a report with a summary of analyses conducted in SAS.

### Course Framework

This class will be taught as a self-paced, asynchronous online course. The instructor will provide datasets and instructions for running various coding functions within SAS. You will apply these functions to import datasets, manipulate these datasets, and produce basic summaries of these datasets.  As the final project of the class, you will produce an independent analysis on a dataset of your own choice that demonstrates the coding techniques and skills that were covered in the course.   

## INSTRUCTOR

Steve Simon (but thanks go to Mary M. Gerkovich who did all the heavy lifting for this class)

Phone: 816-235-6617

E-mail: simons@umkc.edu

Office:	Department of Biomedical and Health Informatics, School of Medicine, M5-117

Office hours:	By appointment; Assistance is available via email and by pre-arranged appointment. Allow up to 24 hours to receive a response from the instructor to an email enquiry. Email enquiries sent outside the regular work week may take longer for a response.

Course Location: On-line

## CATALOG INFORMATION

MEDB 5507-0001

Course Description – This course is an introduction to SAS statistical programming. The course is designed to teach students basic skills that will prepare them to use SAS for data analysis. 
1 credit hour

Prerequisites – none

Course Attributes – graduate research training

Course Format – Lecture, Self-completed assignments, Final project

Course Instructional Mode – Online 


## CLASS STRUCTURE

This class is a self-paced, asynchronous online course.  Course material is organized into six parts.  In order to achieve learning objectives, students need to review provided course materials, including recorded lectures. During the lectures, the instructor will provide coding examples to demonstrate application of SAS, and then students will have hands on programming experience with support and feedback from the instructor. Students have access to the SAS program, either directly on a computer that has SAS installed, through UMKC Remote Labs (http://www.umkc.edu/is/remotelabs/), or through SAS resources (refer below to SAS University under Other Resources).  As the final project of the class, students will independently apply these skills to their own dataset and produce an analysis of these data. 


## STUDENT PROJECTS AND GRADING

Students will be presented with instructions on using SAS functions and/or syntax files and be shown how to apply those to a provided dataset. Under the supervision of the instructor, students will apply these skills to a different provided dataset. At the end of each part, students will turn in material that documents their work process and results, and a brief written interpretation of the work done for that assignment. For the final project, students will use a new dataset of their own choosing, import that dataset, manipulate it as needed, and produce a statistical report using at least one graphical display and at least one descriptive statistical method. The final project must include a written explanation of the results. The dataset you work with for the final project should include four or more variables of which at least two variables are continuous measures and at least two variables are categorical measures.

Grading - This course is graded as Pass / Fail. In order to receive a passing grade, the student must successfully complete the assignments, including the assignment for the final project that includes work using a new dataset provided in the course or your own dataset. This work must be completed and submitted to the instructor by Friday, April 6, 2018 in order to get credit for the course.


## REQUIRED MATERIAL

There is NO required textbook for this class.	
The following books are possible resources you might want to purchase for your future work with SAS. 

*	Delwiche & Slaughter. The Little SAS Book. 5th Edition. SAS Institute Inc., Cary, NC.
*	Cody. Learning SAS by Example : A Programmer’s Guide. SAS Institute Inc., Cary, NC.
*	Cody. SAS Statistics by Example. SAS Institute Inc., Cary, NC.


### Resources

This course will use SAS for all assignments and the final project. Students will have access to the SAS program either directly on a computer that has SAS installed, through UMKC Remote Labs (http://www.umkc.edu/is/remotelabs/), or through SAS resources (refer below to SAS University under Other Resources).  The Department of Biomedical and Health Informatics has student computer workstations available that can be used by arrangement.

Please note that when you are logged onto Remote Labs, it will probably be difficult to have direct access to a drive (USB or hard drive) on the computer you are sitting at (the remote system has a hard time seeing these local devices/ports). You will, however, be able to save files to your Q drive space. When using the UMKC Remote Labs resource, I recommend that you save your course files on your Q drive space or use cloud storage. The Q drive space is part of the UMKC network and your space is automatically mapped when you log onto the UMKC system. If you have questions about how to access this directory, contact UMKC Information Services (816-235-2000). From the Q drive, files can be copied/moved to other storage locations/devices. 

Your Q drive space is limited (approximately 500 mB), so you might want to also consider using cloud storage for your files. Free cloud storage options include – 

* Box.com
* Drop Box
* Google Drive (free with a Google email address)
* Microsoft One Drive

Cloud storage will give you additional space to store files. If you have any question about setting up a cloud storage account using any of these resources, contact UMKC Information Services (816-235-2000). Additional information about Box cloud storage can be viewed on the UMKC web site – http://www.umkc.edu/is/box/


Web Sites (compiled with the help of Dr. Jenifer Allsworth & Michel Conn)

Tutorials - SAS offers many online tutorials - view the complete listing here: http://support.sas.com/training/tutorial/

SAS's basic programming online tutorial is free: 
https://support.sas.com/edu/schedules.html?ctry=us&id=2588

SAS Analytics U - A Youtube channel that includes videos on many topics: https://www.youtube.com/playlist?list=PLVBcK_IpFVi9cajJtRel2uBLbtcLz-WIN
 
The UCLA SAS Starter Kit: http://www.ats.ucla.edu/stat/sas/sk/default.htm 


Other Resources – A favorite SAS instructional site is published by UCLA - http://www.ats.ucla.edu/stat/sas/   
The UCLA site is a fantastic resource for new and experienced SAS users and includes tutorials as well as examples of SAS code.

This paper by a SAS user has a comprehensive listing of websites with training materials and coding tips: http://analytics.ncsu.edu/sesug/2003/TD02-Stojanovic.pdf. Note - Some of the links are broken or out of date. 

UM System Training Opportunities (some Columbia only; low cost)
https://doit.missouri.edu/services/training/classroom-training/course-catalog/sas/

SAS University is free – http://www.sas.com/en_us/software/university-edition.html   

## COURSE OUTLINE 

For each part of the course, the instructor will provide a recorded lecture that shows a demonstration of SAS coding and program execution. In addition, in the Course Content area of the course Blackboard site students will have a Course Outline document (MEDB 5507_Intro to SAS_Course Outline_Notes & Assignments_FS2017.pdf) that provides detailed notes and information on each assignment. Also loaded in the Course Content area will be data files that are not publically available, descriptions of these data files, and the SAS program files used for the recorded coding examples. These coding files can be used as the starting point for your own coding if desired; they can be edited using the SAS program editor, or edited using a text editor and copied into the SAS program editor. It is recomended that you copy these files to a local device (i.e., hard drive or USB drive) to simplify working with the information.

If you are trying to work in SAS at the same time as viewing the recorded lectures, it is recommended that you use a system that will allow you to follow along with the recordings and make notes on the coding as needed. If you are using a system that has 2 monitors, this can be accomplished by playing the recording on one screen and doing other operations on the other screen.

Mp4 versions of all lectures will be created and stored in a « Box » folder that you will have access to. To view these recordings, you need to sign in at – 
	Box.umkc.edu
	Use your SSO
	Look for the folder labeled MEDB 5507 Intro to SAS Recorded Lectures - Fall 2017
This folder will be available to you during the fall semester.

A Discussion Board area (Discussion Forum  Intro to SAS – Questions & Answers) is established in the course Blackboard site in order to have a space for questions and answers that will be available to all students. To post a question on this forum, 
	Click on the Forum name
	Click on « Create Thread » 
	Provide info in the « Subject » box to briefly describe your question (that will allow others to quickly identify a question they are interested in)
	Use the Message box to type in your question
	Hit « Submit »

Note – if you are getting a SAS error message you don’t understand, you can copy the error message into the Description box. If you want a section of coding reviewed because you are having a problem with it, you can also copy the text into the Description box.

The instructor will review and respond to items posted on the Discussion Board on a regular basis. If you have not gotten a response within a day or two, send an email to the instructor asking her to review your question in the discussion forum.


Introduction

* Overview of SAS programming language and program set-up

Part 1 - Initial Steps – Getting Data into SAS and saving SAS dataset

* Setting up SAS library
* Importing data file
* Works pace vs SAS library
* Checking data
* Saving SAS dataset

Part 2 – Modifying Your Dataset

*	Format information
*	Variable labels
* Creating new variables
* Code missing data
* Renaming variables
* Creating a numeric variable from a character variable

Part 3 – Subsetting Your Dataset and Combining Datasets

* Select a subset of variables
* Select a subset of cases
* Combining (concatenating) datasets together – adding observations
* Merging datasets together – adding variables

Part 4 – Examining Relationships Between Variables

* Examine relationships between two categorical variables
* Examine relationships between two continuous variables
* Examine differences between groups on a continuous measure

Part 5 – More Complicated Coding in the Data Step

* Coding subscale scores
* Computing mean scores
* Using an array and do loop to code
* Create a « cut-point » score 

Part 6 – Restructuring Your Datasets

* Create an « horizontal » dataset from a « vertical » dataset
* Create a « vertical » dataset from an « horizontal » dataset

Final Project – DUE DATE : FRIDAY, APRIL13, 2018

* For the final project, use a dataset of your own choosing from those available through this course or a dataset of your own. Demonstrate your mastery of the coding elements covered in the course, including import the dataset, manipulate it as needed, and produce a statistical report using at least one graphical display and at least one descriptive statistical method. This final project should include a written explanation of the coding you performed and the results you obtained. The dataset you work with for this final project should include at least four variables of which two variables represent continuous data and two variables represent categorical data so you can demonstrate your ability to examine relationships between variables.


## COURSE EXPECTATIONS, COURSE POLICIES, REQUIREMENTS, AND STANDARDS FOR STUDENT COURSEWORK AND STUDENT BEHAVIOR

Important UMKC Resources and Policies are applicable to every course and every student at UMKC. These are located in the Blackboard site for this course under the “UMKC Policies” tab. As a UMKC student, you are expected to review and abide by these policies. If you have any questions, please contact your instructor for clarification. In addition to the standard UMKC policies, the Department of Biomedical and Health Informatics includes self-plagiarism in their definition of plagiarism. Self-plagiarism is reuse, without prior discussion and consent of the course director, of an existing paper that has been submitted for credit in a different course.

This course follows the “Faculty allowing recording” option of the Academic Inquiry, Course Discussion and Privacy policy.
