---
title: "Syllabus for Introduction to SAS (MEDB 5507)"
output:
  powerpoint_presentation: default
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

### Documentation about this syllabus

This syllabus was created on 2019-06-04 and last updated on `r Sys.Date()`. It uses R Markdown to create both a Powerpoint presentation and an html document. If you wish to see the R Markdown code, you can find it at [my github site](https://github.com/pmean/introduction-to-SAS/blob/master/basics_syllabus/src/syllabus.Rmd).

```{r echo=FALSE}
suppressMessages(suppressWarnings(library(lubridate)))
suppressMessages(suppressWarnings(library(magrittr)))

semester_start <- "2020-06-08"

dat1 <- as.Date(semester_start, format="%Y-%m-%d")
d <- dat1+(0:15)*7
f <- "%A, %B %d, %Y"
mon <- format(d, f)
tue <- format(d+1, f)
wed <- format(d+2, f)
thu <- format(d+3, f)
fri <- format(d+4, f)

source("prelims.R")
```

### Course information

<!-- regular html comment -->

+ This is an on-line class taught during the eight week summer session. The course starts on `r mon[1]` and ends on `r fri[8]`. Please refer to the [UMKC academic calendar](https://www.umkc.edu/registrar/acal.asp) dates for further information.

+ Note: Many thanks go to Dr. Mary Gerkovich, who provided an excellent structure and format to this class that I will be following closely. 

### Course Instructor

+ Steve Simon 
  + Department of Biomedical and Health Informatics
  + M5-117, School of Medicine Building
  + 816-235-6617
  + simons@umkc.edu
  
+ Check out my [web pages](http://www.pmean.com) and [my blog](http://blog.pmean.com). I am currently trying to combine these into a [single site](http://www.pmean.com/archive/index.html) but this work is still in progress.

<div class="notes">
  
My office is located on the fifth floor of the School of Medicine building in the suite of offices for Biomedical and Health Informatics. 

E-mail is my preferred mode of contact.

</div>

### Office hours

+ Office hours by appointment only. 
  + During the COVID-19 crisis, I will be working almost exclusively from home. I can set up a Zoom videoconfernce for any reasonable day and time.

+ This class is online and asynchronous. You can work on the material at whatever time is convenient to you, as long as you respect the deadlines for discussion boards and assignments.


### Catalog Information

+ Catalog number: MEDB 5507
+ Course Title: Introduction to SAS
+ Credit Hours: 1 credit hours
+ Prerequisites: none
+ Restrictions/exclusions: none
+ Course Attributes: graduate research training
+ Course Format: Lecture, discussion, and individual activities
+ Course Instructional Mode : OA (Online Asyncronous class instruction)

<div class="notes">

Material posted on Canvas course site will support all course activities.

Course Description: Course provides a working familiarity with SAS. Students are not expected to have advanced programming or statistical analysis skills, other than the ability to create and modify text files. Basic methods for data import, data management, simple graphics, and basic statistical analysis are introduced. This class will not cover advanced statistical methods, but will provide the student with a firm foundation to address these areas in advanced statistics classes or in the student's research efforts, including thesis/dissertation research. A basic understanding of statistical terminology and a working familiarity with computer-based data files (e.g., Excel) is necessary.

</div>

### Required and recommended materials

There is NO required textbook for this class.	The following books are possible resources you might want to purchase for your future work with SAS. 

+	Delwiche & Slaughter. The Little SAS Book. 5th Edition. SAS Institute Inc., Cary, NC.
+	Cody. Learning SAS by Example : A Programmer’s Guide. SAS Institute Inc., Cary, NC.
+	Cody. SAS Statistics by Example. SAS Institute Inc., Cary, NC.

### Evaluation and grading criteria

All assignments will be graded on a pass-fail criteria. Students who successfully complete 70% or more of the assignments AND complete the final project will be awarded a passing grade.
 
### Class structure

In general, each class session will consist of a mixture of recorded material available on Canvas as preparation for the session, individual assignments, and discussion/activities that are related to the topic and are completed either individually, within pairs, or within small groups of students. The lecture material is designed to supplement the information assigned from the textbook and other sources.

### Student Learning Objectives

At the end of this course, students will be able to:

1. Read a variety of differently fomatted text files into SAS.

2. Document both the SAS program and the data set it uses.

3. Produce simple descriptive statistics for a variety of data types.

4. Transform and restructure the data.

5. Code missing values.

6. Produce simple graphical displays of your data.
 
### Course Topics

+ inputting delimited text files
+ inputting fixed width text files
+ variable labels, variable formats
+ means, standard deviations, and percentiles
+ missing values
+ transformations
+ scatterplots
+ frequency tables and histograms
+ recoding categorical variables
+ two way cross tabulations
+ boxplots
+ merging
+ longitudinal data
 

### Schedule

Each module should take roughly one week. If a particular topic is causing the class as a whole some difficulty, you may get some extra time for a particular module.

`r read_text("objectives01", path="../basics1/data")`

`r read_text("objectives02", path="../basics2/data")`

`r read_text("objectives03", path="../basics3/data")`

`r read_text("objectives04", path="../basics4/data")`

`r read_text("objectives05", path="../basics5/data")`


+ Module 1, Reading data from a variety of text formats. Variable labels. Missing value codes. Means, standard deviations, and percentiles. Histograms and scatterplots. Functional transformations. Program documentation.

+ Module 2, Categorical data. Variable formats. Recoding category levels. Indicator variables. Counts and percentages. Two way crosstabulations. Data dictionary.

+ Module 3, Boxplots. Group means and standard deviationss. Report formats.

+ Module 4, Merging. Longitudinal data. Tall and thin format. Short and fat format.

+ Module 5, Independent project

Student learning outcomes

At the end of this course, students will be able to:

1. Read a variety of differently fomatted text files into SAS.

2. Document both the SAS program and the data set it uses.

3. Produce simple descriptive statistics for a variety of data types.

4. Transform and restructure the data.

5. Code missing values.

6. Produce simple graphical displays of your data.

### Course Requirements

Students are responsible for viewing all the videos, running the example programs shown in the videos, and then running similar programs using different data sets. Students must participate in discussion boards, take short quizzes, and prepare a final project.

### Course expectations

Students must complete all assignments on time. If special circumstances arise, a student may request an extension of up to one week for all the work in a particular module. This request must be made prior to the due date of the work in a module.


### Policies

<!-- 
  List the course specific policies first, then
  the institutional policies. Institutional 
  policies inlcude:
    Honor policy,
    Academic calendar,
    Campus safety,
    Disability support services,
    Grade appeal policy.
-->

`r read_text("syllabus-policies-canvas")`

Acrobat Reader may be downloaded for FREE from the [Adobe website](http://www.adobe.com/products/acrobat/readstep2.html).

`r read_text("syllabus-policies-email")`

`r read_text("syllabus-policies-discussion")`

`r read_text("syllabus-policies-conduct")`

Please refer to the 
[UM System standard of conduct](http://www.umsystem.edu/ums/rules/collected_rules/programs/ch200/200.010_standard_of_conduct) for more information.

`r read_text("syllabus-policies-honesty")`

`r read_text("syllabus-policies-attendance")`

`r read_text("syllabus-policies-discrimination")`

Discrimination Grievance Procedures for Students: Discrimination Grievance Procedures for Students can be found [here](http://www.umsystem.edu/ums/rules/collected_rules/grievance/ch390/grievance_390.010).

`r read_text("syllabus-policies-english-proficiency")`

`r read_text("syllabus-policies-grade-appeal")`

In the event a student would like to appeal a course grade they must follow the School of Medicine procedure for grade appeal for graduate courses, which is outlined in the student handbook or can be found at the [School of Medicine Graduate Council web page](http://med.umkc.edu/councils/graduate/documents/).

### Resources

Academic Calendar: Students are encouraged to review important add, drop or withdraw dates: https://www.umkc.edu/calendar/

Campus Safety: [Inclement weather, mass notification, and emergency response guide](http://www.umkc.edu/umkcalert/).

Counseling and Health Services Available at UMKC: UMKC students may experience many challenges in their lives while attending college – stress, depression, suicidality, trauma, relationship issues, health concerns, etc. As your professor I care about your success and well-being, and want to make you aware of some helpful resources on campus. The [UMKC Counseling Center](www.umkc.edu/counselingcenter), located at 4825 Troost in Room 206, offers a wide range of supportive services to students. Appointments can be made by calling 816.235.1635. [UMKC Student Health and Wellness](http://info.umkc.edu/studenthealth/), located at 4825 Troost in Room 115, offers a full range of health care and promotion services. Appointments can be scheduled online or by calling 816.235.6133. The [MindBody Connection](www.umkc.edu/mindbody) is located in the Atterbury Student Success Center in Room 112 and offers a variety of stress-reduction services.

Disability Support Services: To obtain disability related accommodations and/or auxiliary aids, students with disabilities must contact the Office of Services for Students with Disabilities (OSSD) as soon as possible. To contact OSSD, call (816) 235-5696 or visit their website. Once verified, OSSD will notify the course instructor and outline the accommodation and/or auxiliary aids to be provided. UMKC has a [web page](http://www.umkc.edu/disability/) with more information about disability services.

Severe Weather Policy: Cancellation of classes will be posted on the front page of the [University’s website](www.umkc.edu) as well as through the UMKC Alert message system.

Statement of Human Rights: The Board of Curators and UMKC are committed to the policy of equal opportunity, regardless of race, color, religion, sex, sexual orientation, national origin, age, disability and status as a Vietnam era veteran. Commitment to the policy is mentored by the [Division of Diversity Equity](https://info.umkc.edu/diversity/), but it is the responsibility of the entire university community to provide equal opportunity through relevant practices, initiatives and programs.

Title IX: Under the University of Missouri’s Title IX policy, discrimination, violence and harassment based on sex, gender, and gender identity are subject to the same kinds of accountability and support applied to offenses based on other protected characteristics such as race, color, ethnic or national origin, sexual orientation, religion, age, ancestry, disability, military status, and veteran status. If you or someone you know has been harassed or assaulted, you can find the appropriate resources by visiting [UMKC’s Title IX Office webpage](http://info.umkc.edu/title9/) or contacting UMKC’s Title IX Coordinator, Mikah K. Thompson (816.235.6910 or thompsonmikah@umkc.edu). Additionally, you can file a complaint using [UMKC’s online discrimination complaint form](http://info.umkc.edu/title9/reporting/report-online/).

While most UMKC employees are required to report any known or suspected violation of Title IX, students may seek confidential guidance from the following campus locations: UMKC Counseling Service Volker Campus 4825 Troost Ave, Suite 206 Kansas City, MO 64110 Phone – (816) 235-1635 UMKC Counseling Service Health Sciences Campus Health Sciences Building 1418 2464 Charlotte Kansas City, MO 64108 Phone – (816) 235-1635 (open Tuesdays, 1-5pm) Student Health and Wellness 4825 Troost Ave., Suite 115 Kansas City, MO 64110 Phone - (816) 235-6133

