---
title: "Your first SAS program"
author: "Steve Simon"
date: "8/12/2019"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Your first SAS program

<div class="notes">

I want to show how to use SAS. I had the screen resolution too high. It is now 800 by 600 and I think it is like going back.

I like to get rid of a couple of windows and use tile vertical for the rest.

Take baby steps. If you can't run this program, talk to me face-to-face.

You should try typing in the program like I am doing. It helps.

I like to put lots of blank lines in.

Normally you would use a two part name. Not here. This is a simple throw-away example, so it can use a one part name. That means it disappears.

Here is where we type the data. At the end you put in another run statement.

This is bad form. Normally you put the data in a separate file.

I like the obs option a lot.

I'll put in a title as well.

I'm going to indent a bit less.

The thing I always worry about is leaving out a semicolon.

There is no autosave feature.

SAS uses a stupid default 9.4. If you are using a network computer, you want to use a network folder, typically the Q drive.

I don't do this, but do what I preach, not what I do.

I'm going to create a new folder. I can't decide on a name. Am I indecisive? I want to set up a logical directory structure, but I also want it to be reasonably flat. I tend to save things in a folder called "source" (SRC).

The run guy is a guy who looks like he is running.

You see some diagnostic information. Work is a scratch. We are not using this again. Three observations, but then one because we said obs=1.

There is the output. SAS by default centers things, and it doesn't work well with 800 by 600.

Try this yourself. It's a baby step. If it works then you can take more baby steps.

</div>