---
title: "Create overviews of key files for each module"
author: "Steve Simon"
date: "Created 2021-07-28"
output: html_document
---

```{r common-code, child="common-functions.Rmd"}
```

```{r}
list.files(path="../src", pattern="\\.sas") %>%
  str_subset("-hw0", negate=TRUE) -> sas_v

list.files(path="../src", pattern="\\.sas") %>%
  str_subset("-hw0") -> sas_h

list.files(path="../src", pattern="\\.Rmd") -> slides_r

sas_v
sas_h
slides_r
```

```{r}
readLines("create-module-overviews.txt") %>%
  paste0(collapse="\n") -> module_overviews
```

```{r}
module_overviews %<>% paste0("\n\nThis file was last updated on ", Sys.Date())
```

```{r}
for (module in modules) {
  sas_v %>% str_subset(paste0(module, "-")) -> sas_subset
  module_overviews %0% 
    "\n\n### Module" %0%
    module %0% 
    ", SAS programs used in the videos\n" -> module_overviews
  module_overviews %<>% paste0("\n", bullet(sas_subset))
  
  sas_h %>% str_subset(paste0(module, "-")) -> sas_subset
  module_overviews %0% 
    "\n\n### Module" %0%
    module %0% 
    ", Homework solutions, SAS code\n" -> module_overviews
  module_overviews %<>% paste0("\n", bullet(sas_subset))
  
  
}
```

```{r}
module_overviews %<>% paste0("\n\n", add_links(sas_v, "sas", "src/"))
module_overviews %<>% paste0("\n\n", add_links(sas_h, "sas", "src/"))
```

```{r}
module_overviews %>% cat
module_overviews %>%
  writeLines("../modules/5507-module-overviews.md")
```

