---
title: "Overview for Module1"
output:
  html_document: default
  pdf_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This file was created by Steve Simon using R Markdown on 2020-06-27 and last updated on `r Sys.Date()`. You can find the source code on [my github repository](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/overview1.Rmd).

### Learning objectives

`r paste(readLines("../data/objectives01.txt")[-1], collapse="\n")`

### SAS code that you will learn

+ data
+ delimiter
+ filename
+ infile
+ input
+ ods
+ proc print
+ run
+ title

### Videos and handouts

+ V01-01. Getting started (16 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3c8860e3-ec58-4873-ba83-aa68012a84c2).
  + Slides with speaker notes available in [pdf format](https://github.com/pmean/introduction-to-SAS/blob/master/basics1/results/getting-started.pdf).

+ V01-02. History of SAS (8 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ba88be23-73d8-4804-ada4-aa73011ac94a). 
  + Slides with speaker notes are not available.

+ V01-03. Your first SAS program (10 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=671572b5-a25a-46e0-8d85-aa730122496b).
  + Slides with speaker notes are not available.
  + your-first-program.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/your-first-program.sas).

+ V01-04. Storing SAS datasets using libname (12 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a8dbb622-2d61-41a7-b6a4-aa7301264e3e).
  + Slides with speaker notes are not available.
  + permanent-storage.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/permanent-storage.sas).
  + re-use.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/re-use.sas).

+ V01-05. Storing SAS output using ODS (15 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=cebf1a98-06bf-41e0-9be1-aa7301384dc6).
  + Slides with speaker notes are not available.
  + saved-pdf.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/saved-pdf.sas).
  + saved-html.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/saved-html.sas).

+ V01-06. Reading external data using infile and filename (13 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=faeefa60-c4ed-4d5b-a959-aa73013ea6af).
  + Slides with speaker notes are not available.
  + input-text.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/input-text.sas).
