---
title: "Storing SAS datasets using libname"
author: "Steve Simon"
date: "8/12/2019"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Storing SAS datasets

<div class="notes">

We're back. If you're listening to this video, you got the first program running.

I'm mourning the loss of this data set.

To save the data permanenty, use the libname statement.

I'll call it permanent.

We have to figure out where we are. I'm guessing documents/results.

There is a standard, storing new information in a results directory.

if you have any trouble accessing the Q drive, let me know.

Create a new folder called results.

Double click to enter it.

It turns out that in Windows, case insensitive. SAS also.

Hold your breath, let's try running this. 

It annoys me about SAS, it keeps the log around.

Use clear all on the log window. Use clear all on the output window as well.

Hit the little running guy.

Permanent is not a valid SAS name.

It exceeds eight characters. Oh the pain. SAS was built in the 1960s. String constants, for the most part, has to fit in the same space as a floating point number. This means eight characters. SAS since in the 1960's, has some legacy issues.

Say data perm. It sounds like we're hair stylists now.

Two partr name that means it's going to be stored.

Did I say it wouldn't run the first time. I was right. Do we want to save it under the same name.

Let's call the permanent-storage.sas. I have to change it up here as well.

I'm typing it live. I want you to learn that the best way is to type rather than use cut-and-paste. It makes a lot of sense to type this in.

The file is not stored yet. You can see an asterisk. Hold your breath. I think it will run the second time.

Let's make this big so we can see. We're happy because there is no red.

Let me go back to computer and the Q drive and the documents folder and results.

The extension is eight characters, sas7bdat. The most ridiculous extension I have ever seen.

I'm going to exit. Are you sure? Now I'm going to show something cool here.

SAS do this and this and tile. Because it is stored permanently. It always wants to store in 9.4. I'm going to use the Q drive. Documents, SAS programs. What's under source? The interesting thing is I can get rid of the data step now and rename the program. File save as, re-sue.sas. Save. Let's take a careful look. There is no data step anymore. Just call it from perm.simple_example. This program will work now without a data step. It's find of fun in a geeky way. Libname works. Only only observation because of obs=1. Do this baby program. It is storing your data using a two part name.

</div>