---
title: "Introduction to SAS, Working with categorical variables"
author: "Steve Simon"
date: "Created: 2021-05-30"
output: powerpoint_presentation
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

```{r common-code, child="common-functions.Rmd"}
```


### Overview

+ Frequency counts
+ Convert string to numeric
+ Labels for number codes
+ Drawing bar charts
+ Converting continuous to categorical
+ Modifying categorical variables
+ Crosstabulations

<div class="notes">

author: Steve Simon
date: created 2021-05-30
purpose: to produce slides for module04 videos
license: public domain

Here is an overview of what I want to cover in this module.

We're going to look at a different data set, one with mostly categorical variables. I'll introduce proc format, which allows you to attach labels to categorical data, talk about recoding, and show some tables using proc freq. I'll also show you a simple bar chart.

[For my own use]General structure of this program.

`r general_structure`

</div>

### SAS code: `r ti(tx, i=0)` <!--documentation header-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 1)` <!--where to find and store things-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 2)` <!--import-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 3)` <!--print-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 3)`
`r ou(1)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 4)` <!--freq-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 4)`
`r ou(2)`
`r no(tx, part=2)`
### SAS output: `r ti(tx, 4)`
`r ou(3)`
`r no(tx, part=3)`

### Break #1
+ What have you learned
  + Frequency counts
+ What's coming next
  + Convert string to numeric

### SAS code: `r ti(tx, 5)`  <!--convert-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 5)`
`r ou(4)`
`r no(tx, part=2)`

### Break #2
+ What you have learned
  + Convert string to numeric
+ What's coming next
  + Labels for number codes

### SAS code: `r ti(tx, 6)` <!--format-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 6)` 
`r ou(5)`
`r no(tx, part=2)`

### Break #3
+ What you have learned
  + Labels for number codes
+ What's coming next
  + Drawing bar charts

### SAS code: `r ti(tx, 7)` <!--bar chart 1-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 7)` 
`r ou(6)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 8)` <!--bar chart 2-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 8)` 
`r ou(7)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 9)` <!--bar chart 3-->
`r co(tx, 9)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 9)` 
`r ou(8)`
`r no(tx, part=2)`

### Break #4
+ What you have learned
  + Drawing bar charts
+ What's coming next
  + Converting continuous to categorical

### SAS code: `r ti(tx, 10)` <!--converting 1-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 11)` <!--converting 2-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 11)` 
`r ou(9)`
`r no(tx, part=2)`
### SAS output: `r ti(tx, 11)` 
`r ou(10)`
`r no(tx, part=3)`
### SAS output: `r ti(tx, 11)` 
`r ou(11)`
`r no(tx, part=4)`

### SAS code: `r ti(tx, 12)` <!--converting 3-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 13)` <!--converting 4-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 14)` <!--converting 5-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 14)` 
`r ou(12)`
`r no(tx, part=2)`
### SAS output: `r ti(tx, 14)` 
`r ou(13)`
`r no(tx, part=3)`
### SAS output: `r ti(tx, 14)` 
`r ou(14)`
`r no(tx, part=4)`

### Break #5
+ What you have learned
  + Converting continuous to categorical
+ What's coming next
  + Modifying categorical variables

### SAS code: `r ti(tx, 15)` <!--modifying-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 15)` 
`r ou(15)`
`r no(tx, part=2)`

### Break #6
+ What you have learned
  + Modifying categorical variables
+ What's coming next
  + Crosstabulation

### SAS code: `r ti(tx, 16)` <!--crosstabulation 1-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 16)`
`r ou(16)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 17)` <!--crosstabulation 2-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 17)`
`r ou(17)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 18)` <!--crosstabulation 3-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 18)`
`r ou(18)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 19)` <!--crosstabulation 4-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 19)`
`r ou(19)`
`r no(tx, part=2)`

### Review
+ Frequency counts
+ Convert string to numeric
+ Labels for number codes
+ Drawing bar charts
+ Converting continuous to categorical
+ Modifying categorical variables
+ Crosstabulations

