---
title: "Introduction to SAS, Working with a mix of categorical and continuous variables"
author: "Steve Simon"
date: "Created: 2019-07-19"
output: powerpoint_presentation
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

```{r common-code, child="extract-sas.Rmd"}
```

### Overview

+ Review
  + proc format, proc freq, proc means
+ proc corr
+ proc sgplot
  + scatterplot
  + boxplot
+ by statement

<div class="notes">

author: Steve Simon
date: Created 2021-05-30
purpose: to produce slides for module05 videos
license: public domain

Here is an overview of what I want to cover in module05. 

[For my own use]General structure of this program.

`r general_structure`

</div>

### SAS code: `r ti(tx, 0)` <!--documentation header-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 1)` <!--where to find and store things-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 2)` <!--label-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 3)` <!--read-->
`r co(tx)`
`r no(tx)`

### SAS code: `r ti(tx, 4)` <!--print-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 4)`
`r ou(1)`
`r no(tx, part=2)`


### SAS code: `r ti(tx, 5)` <!--means and freqs-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 5)`
`r ou(2)`
`r no(tx, part=2)`
### SAS output: `r ti(tx, 5)`
`r ou(3)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 6)` <!--corr-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 6)`
`r ou(4)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 7)` <!--scatter-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 7)`
`r ou(5)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 8)` <!--loess-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 8)`
`r ou(6)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 9)` <!--vbox-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 9)`
`r ou(7)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 10)` <!--by-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 10)`
`r ou(8)`
`r no(tx, part=2)`

### SAS code: `r ti(tx, 11)` <!--sgplot and means-->
`r co(tx)`
`r no(tx, part=1)`
### SAS output: `r ti(tx, 11)`
`r ou(9)`
`r no(tx, part=2)`
### SAS output: `r ti(tx, 11)`
`r ou(10)`
`r no(tx, part=3)`
